kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-fileserver
spec:
  # storageClassName: glusterfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: efs-fileserver